In [ ]:
#what is NumPy?
#NumPy is a Python library used for working with arrays.
#It also has functions for working in domain of linear algebra, fourier transform, and matrices.
#NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
#NumPy stands for Numerical Python.
#Import numpy as np

In [ ]:
#create single a NumPy array
import numpy as np

[2 4 6]


In [2]:
# Creating a NumPy array from a Python list
my_list = [[1, 2, 3, 4, 5]]
my_array = np.array(my_list) # Convert the list to a NumPy array

print("Python List:", my_list)
print("NumPy Array:", my_array)

Python List: [[1, 2, 3, 4, 5]]
NumPy Array: [[1 2 3 4 5]]


In [52]:
#create a 2D NumPy array
Num_values = np.array([[2,4,6],[1,3,5]])
print(f'The 2D NumPy array is: \n {Num_values}')

The 2D NumPy array is: 
 [[2 4 6]
 [1 3 5]]


In [30]:
#Create a 3D NumPy array
Num_values = np.array([
    [[2,4,6],
     [1,3,5],
    [7,9,11]]
])
print(f'The 3D NumPy array is: \n {Num_values}')



The 3D NumPy array is: 
 [[[ 2  4  6]
  [ 1  3  5]
  [ 7  9 11]]]


In [53]:
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

print("Element at index 2 in arr1:", arr1[2])
print("Elements from index 1 to 3 in arr1:", arr1[1:4])
print("Element at row 1, column 2 in arr2:", arr2[1, 2])
print("First two rows and columns in arr2:\n", arr2[:2, :2])

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Element at index 2 in arr1: 3
Elements from index 1 to 3 in arr1: [2 3 4]
Element at row 1, column 2 in arr2: 6
First two rows and columns in arr2:
 [[1 2]
 [4 5]]


In [44]:
#ndim
#NumPy arrays have an attribute called ndim that returns the number of dimensions that the array has.
numberOfDimensions = Num_values.ndim
print(f'The number of dimensions in the NumPy array is: {numberOfDimensions}')

The number of dimensions in the NumPy array is: 3


In [3]:
# Create a 1D NumPy array with elements from 10 to 50.
array_values = np.arange(10,50)
print(array_values)
# Access the 5th element of the array you created in question 1.
print(f'The 5th elemet in the arrary is :{array_values[4]}')
# Slice the array to get elements from index 3 to 8.
print(f'{array_values[3:8]}')

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
The 5th elemet in the arrary is :14
[13 14 15 16 17]


In [ ]:
#add the two arrays element wise
print(f'Adding the two arrays element wise: {array_values + array_values}')
print(f'The Sum i:',sum(array_values))
print(f'Mean is :',np.mean(array_values))
print(np.std(array_values))

Adding the two arrays element wise: [20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
The Sum i: 1180
Mean is : 29.5
11.543396380615196
['10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '20' '21' '22' '23'
 '24' '25' '26' '27' '28' '29' '30' '31' '32' '33' '34' '35' '36' '37'
 '38' '39' '40' '41' '42' '43' '44' '45' '46' '47' '48' '49']


In [5]:
#convert the array to a string
convert = array_values.astype(str)
print(convert)

['10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '20' '21' '22' '23'
 '24' '25' '26' '27' '28' '29' '30' '31' '32' '33' '34' '35' '36' '37'
 '38' '39' '40' '41' '42' '43' '44' '45' '46' '47' '48' '49']


In [7]:
# 1. Create a 1D array
arr1 = np.arange(10, 51)
print("1D Array:", arr1)
# 2. Array Indexing
print("5th element:", arr1[4])
# 3. Array Slicing
print("Elements from index 3 to 8:", arr1[3:9])
# 4. Basic Arithmetic Operations
arr2 = np.arange(50, 91)
print("Second 1D Array:", arr2)
# Element-wise addition
print("Element-wise addition:", arr1 + arr2[:len(arr1)])

1D Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
5th element: 14
Elements from index 3 to 8: [13 14 15 16 17 18]
Second 1D Array: [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
Element-wise addition: [ 60  62  64  66  68  70  72  74  76  78  80  82  84  86  88  90  92  94
  96  98 100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130
 132 134 136 138 140]


In [ ]:
# Element-wise multiplication
print("Element-wise multiplication:", arr1 * arr2[:len(arr1)])
# 5. Aggregation Functions
print("Sum of arr1:", np.sum(arr1))
print("Mean of arr1:", np.mean(arr1))
print("Standard deviation of arr1:", np.std(arr1))
# 6. Dot Product
print("Dot product:", np.dot(arr1, arr2[:len(arr1)]))
# 7. Generating Random Numbers
random_arr = np.random.rand(10)
print("Random array:", random_arr)
random_ints = np.random.randint(1, 101, size=10)
print("Random integers:", random_ints)

Element-wise multiplication: [ 500  561  624  689  756  825  896  969 1044 1121 1200 1281 1364 1449
 1536 1625 1716 1809 1904 2001 2100 2201 2304 2409 2516 2625 2736 2849
 2964 3081 3200 3321 3444 3569 3696 3825 3956 4089 4224 4361 4500]
Sum of arr1: 1230
Mean of arr1: 30.0
Standard deviation of arr1: 11.832159566199232
Dot product: 91840
Random array: [0.66779616 0.51837113 0.37602788 0.19916761 0.57745571 0.67673011
 0.12578928 0.94970354 0.29996401 0.38285656]
Random integers: [38 87 19 44 43 54 48  5 59 76]
