In [ ]:
# What is NumPy?
# NumPy is a powerful library for numerical computing in Python. It provides support for arrays, matrices, 
# and many mathematical functions to operate on these data structures efficiently.
#! pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np

In [27]:
import numpy as np

# Creating a NumPy array from a Python list
my_list = [[1, 2, 3, 4, 5]]
my_array = np.array(my_list)

print("Python List:", my_list)
print("NumPy Array:", my_array)

Python List: [[1, 2, 3, 4, 5]]
NumPy Array: [[1 2 3 4 5]]


In [32]:
print(f'The Type of the List is {type(my_list)}')
print(f'No of Dimensions in the List is {np.ndim(my_list)}')
print(f'The Shape of the List is {np.shape(my_list)}')

The Type of the List is <class 'list'>
No of Dimensions in the List is 2
The Shape of the List is (1, 5)


In [34]:
mymatrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mymatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
